-- Add GST / ITC fields to Expense (per accountant SOP)
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "vendorName" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "vendorGstin" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "billNo" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "taxableAmount" DOUBLE PRECISION;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "gstPercent" DOUBLE PRECISION;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "gstAmount" DOUBLE PRECISION;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "itcEligible" BOOLEAN NOT NULL DEFAULT false;
